name: Build and release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build simpleid-tool
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: bz2, Phar
          ini-values: phar.readonly=0
          tools: composer

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: "composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "composer-"

      - name: Install dependencies
        run: composer update && composer install

      - name: Build phar
        run: composer phar

      - name: Upload simpleid-tool.phar
        uses: actions/upload-artifact@v2
        with:
          name: simpleid-tool
          path: simpleid-tool.phar

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download simpleid-tool.phar
        uses: actions/download-artifact@v2
        with:
          name: simpleid-tool

      - name: Get semantic version
        id: semver
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '\/v(.*)$'

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: simpleid-tool.phar
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ !!steps.semver.outputs.prerelease }}
